dist: xenial

sudo: true

os: linux

language: cpp

addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                        - g++-5
                        - boost1.67
script:
        - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-r cmake .
        - cmake --build . -- -j2
