dist: xenial

sudo: true

os: linux

language: cpp

addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                        - g++-5
                        - libboost-all-dev
                        - flex
                        - bison
                        - qtbase5-dev
                        - libgl1-mesa-dev
                        - libglu1-mesa-dev
                        - freeglut3-dev
                        - libglew-dev
                        - libpng16-dev

script:
        - mkdir build
        - cd build
        - ls /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
        - cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-5 -DCMAKE_CXX_COMPILER=/usr/bin/g++-5 -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL ..
        - make -j 2
