dist: xenial

sudo: true

os: linux

language: cpp

addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                        - g++-5
                        - libboost-all-dev
script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-5 -DCMAKE_CXX_COMPILER=/usr/bin/g++-5 ..
        - make -j 2
