dist: xenial

sudo: true

os: linux

language: cpp

addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                        - g++-5
                        - build-essential
                        - cmake
                        - libboost-all-dev
                        - flex
                        - bison
                        - libgl1-mesa-dev
                        - libglu1-mesa-dev
                        - freeglut3-dev
                        - libglew-dev
                        - libpng16-dev
                        - qtbase5-dev
before_install:
        - wget http://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-linux-x64-5.7.0.run
        - chmod +x qt-opensource-linux-x64-5.7.0.run
        - ./qt-opensource-linux-x64-5.7.0.run

script:
        - mkdir build
        - cd build
        - ls /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
        - sudo find / -type f -name "Qt5OpenGLConfig.cmake"
        - sudo find / -type d -name "Qt5OpenGL"
        - cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-5 -DCMAKE_CXX_COMPILER=/usr/bin/g++-5 -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL ..
        - make -j 2
